In [6]:
# @author: lajello

# Transform data and handle missing values. Two example datasets are provided.

# REFERENCES: 
# Kaggle survey: https://www.kaggle.com/kaggle/kaggle-survey-2018
# Crunchbase research paper: https://www.nature.com/articles/s41599-020-00685-7

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Kaggle survey

In [8]:
df_kaggle = pd.read_csv('data/kaggle_datascience.csv')
print(len(df_kaggle))
df_kaggle.head()

23859

,gender,age,country,education_level,role,years_of_experience,salary
0,Female,45-49,United States of America,Doctoral degree,Consultant,NaN,NaN
1,Male,30-34,Indonesia,Bachelor’s degree,Other,5-10,"10-20,000"
2,Female,30-34,United States of America,Master’s degree,Data Scientist,0-1,"0-10,000"
3,Male,35-39,United States of America,Master’s degree,Not employed,NaN,NaN
4,Male,22-24,India,Master’s degree,Data Analyst,0-1,"0-10,000"

In [9]:
# salary and age are saved as strings!
df_kaggle['salary'].unique()

<StringArray>
[                                                           nan,
                                                    '10-20,000',
                                                     '0-10,000',
 'I do not wish to disclose my approximate yearly compensation',
                                                    '20-30,000',
                                                  '125-150,000',
                                                    '30-40,000',
                                                    '50-60,000',
                                                  '100-125,000',
                                                   '90-100,000',
                                                    '70-80,000',
                                                    '80-90,000',
                                                    '60-70,000',
                                                  '400-500,000',
                                                    '40-50,000',
                                                  '150-200,000',
                                                     '500,000+',
                                                  '300-400,000',
                                                  '200-250,000',
                                                  '250-300,000']
Length: 20, dtype: str

In [ ]:
# EXERCISE 1:

# WRITE A FUNCTION that transforms age string to a number 
def parse_age(age_str):
    # take input a string, return an integer
    return
    
# WRITE A FUNCTION that transforms a salary string to a number
def parse_salary(salary_str):
    # take input a string, return an integer
    return
    
# WRITE SOME CODE TO apply the two functions above to your dataframe
df_kaggle.head()

,gender,age,country,education_level,role,years_of_experience,salary
0,Female,45-49,United States of America,Doctoral degree,Consultant,NaN,NaN
1,Male,30-34,Indonesia,Bachelor’s degree,Other,5-10,"10-20,000"
2,Female,30-34,United States of America,Master’s degree,Data Scientist,0-1,"0-10,000"
3,Male,35-39,United States of America,Master’s degree,Not employed,NaN,NaN
4,Male,22-24,India,Master’s degree,Data Analyst,0-1,"0-10,000"

In [ ]:
# EXERCISE 2: 
# WRITE SOME CODE TO fill the null values of salary with the median salary

In [15]:
#df_kaggle[['gender','salary']].groupby('gender').isna().count()
#df_kaggle.salary.isnull().groupby(df_kaggle['gender']).sum().astype(int).reset_index(name='count')
df_missing = df_kaggle.salary.isna().groupby(df_kaggle['gender']).sum()
df_all = df_kaggle.salary.groupby(df_kaggle['gender']).count()
df_missing / df_all

gender
Female                     0.236128
Male                       0.168722
Prefer not to say          0.387755
Prefer to self-describe    0.112676
Name: salary, dtype: float64

## Crunchbase

The `jobs.csv` file is too large to be pushed to GitHub and must be manually downloaded. Find it under todays lecture on LearnIt.

In [16]:
df_jobs = pd.read_csv('./data/jobs.csv')

In [17]:
df_jobs.columns

Index(['person_uuid', 'org_uuid', 'started_on', 'ended_on', 'is_current',
       'title', 'job_role', 'executive_role', 'advisory_role'],
      dtype='str')

In [18]:
# count how many null entries there are in each field
for c in df_jobs.columns:
    print(c, len(df_jobs[df_jobs[c].isna()]))

person_uuid 0
org_uuid 2279
started_on 2078940
ended_on 2992897
is_current 4383
title 117
job_role 0
executive_role 0
advisory_role 0

In [19]:
# simple hot deck imputation: the field "is_current" can be inferred from other fields
has_startend = (df_jobs.is_current.isna()) & ~(df_jobs.started_on.isna()) & ~(df_jobs.ended_on.isna())
df_jobs.loc[has_startend,'is_current'] = df_jobs.loc[has_startend,'is_current'].fillna('f')

In [ ]:
# OPEN EXPLORATION EXERCISE 3: try out other fields and strategies for missing data management in both datasets

In [ ]:
# EXERCISE SOLUTIONS BELOW

In [ ]:
# EXERCISE 1 SOLUTION:
# transform age and salary to numbers 
# def parse_age(age_str):
#     try:
#         low,high = age_str.split('-')
#         age_number = math.floor(np.mean([int(low),int(high)]))
#         return age_number
#     except:
#         return None
    
# def parse_salary(salary_str):
#     try:
#         salary = int(salary_str.split('-')[0])*1000
#         return salary
#     except:
#         return None
    
# df['age_number'] = df['age'].apply(parse_age)
# df['salary_number'] = df['salary'].apply(parse_salary)

In [ ]:
# EXERCISE 2 SOLUTION: fill the null values of salary with the median salary
# df_kaggle.salary_number = df_kaggle.salary_number.fillna(df_kaggle.salary_number.median())
# df_kaggle.head()